# Generated by Django 4.0 on 2021-12-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('country_code', models.CharField(max_length=2, verbose_name='Код страны')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
    ]
